server:
  port: 8888
spring:
  application:
    name: proxy
eureka:
  client:
    # 配置注册中心地址
    service-url:
      defaultZone: http://localhost:8761/eureka/

#这个可以不配置，会默认用服务注册到eureka上的
#zuul:
#  routes:
#    userApi:
#      path: /user/**
#      serviceId: user
#    orderApi:
#      path: /order/**
#      serviceId: order
#  host:
#    connect-timeout-millis: 60000
#    socket-timeout-millis: 60000
ribbon:
  ReadTimeout: 15000
  ConnectTimeout: 15000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000