server:
  port: 8081
spring:
  application:
    name: user
eureka:
  client:
    # 配置注册中心地址
    service-url:
      defaultZone: http://localhost:8761/eureka/
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000