server:
  port: 9000
spring:
  application:
    name: config-server
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    bus:
      trace:
        enabled: true
    # 配置中心配置
    config:
      server:
        git:
          uri: https://github.com/xkcoding/spring-cloud-learning-simple-demo-config
          default-label: master
eureka:
  client:
    # 配置注册中心地址
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh